/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import client.Client;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import model.Coordinate;
import model.Player;
import model.UserDisconnected;

/**
 *
 * @author conqu
 */
public class GameGUI extends javax.swing.JFrame {

    public static final String TITLE = "Caro(%dx%d) You are playing against %s as %s";
    public static final String CURRENT_USER_INFO = "%s: %s";

    private Client client;
    private CaroScene caroScene;
    private Player player;
    private final int size;
    private int oneBlockSize;

    private boolean myTurn;

    private void createGameScene() {
        caroScene = new CaroScene(size);
        gameScene.setLayout(new CardLayout());
        gameScene.add(caroScene);

        myTurn = player.isInitiate();

        // Title
        this.setTitle(String.format(TITLE, size, size, player.getOpponentName(), player.getMyName()));

        // Player info
        this.playerNameLb.setForeground(Color.blue);
        this.playerNameLb.setText(
                String.format(CURRENT_USER_INFO,
                        "You: ", myTurn ? Player.PLAYER_X : Player.PLAYER_O));

        // First turn
        this.turnLb.setText(Player.PLAYER_X);

        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);
        this.oneBlockSize = gameScene.getPreferredSize().height / size;
    }

    protected void rematch() {
        player = player.switchSide();
        myTurn = player.isInitiate();
        this.turnLb.setText(Player.PLAYER_X);
        this.playerNameLb.setText(
                String.format(CURRENT_USER_INFO,
                        player.getMyName(), myTurn ? Player.PLAYER_X : Player.PLAYER_O));
    }

    private void playerMove(Coordinate coordinate) {
        myTurn = !myTurn;
        this.turnLb.setText(player.getMyName());
        this.caroScene.playerMove(coordinate);
        this.client.sendObject(coordinate);
    }

    public void opponentMove(Coordinate coordinate) {
        myTurn = !myTurn;
        this.turnLb.setText(player.getOpponentName());
        this.caroScene.opponentMove(coordinate);
    }

    public void opponentDisconnect() {
        JOptionPane.showMessageDialog(null, player.getOpponentName() + " has left the game.");
        this.dispose();
    }

    private void disconnect() {
        client.sendObject(new UserDisconnected(
                player.getMyName(), player.getOpponentName()));
        this.dispose();
    }

    private void setLookAndFeel() {
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(GameGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form GameGUI
     * @param player
     * @param size
     * @param client
     */
    public GameGUI(Player player, int size, Client client) {
        this.player = player;
        this.size = size;
        this.client = client;

        initComponents();
        setLookAndFeel();
        createGameScene();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameScene = new javax.swing.JPanel();
        playerNameLb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        turnLb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        gameScene.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                gameSceneComponentRemoved(evt);
            }
        });
        gameScene.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameSceneMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gameSceneLayout = new javax.swing.GroupLayout(gameScene);
        gameScene.setLayout(gameSceneLayout);
        gameSceneLayout.setHorizontalGroup(
            gameSceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );
        gameSceneLayout.setVerticalGroup(
            gameSceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        playerNameLb.setText("           ");

        jLabel2.setText("Turn: ");

        turnLb.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerNameLb)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(turnLb))
                    .addComponent(gameScene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerNameLb)
                    .addComponent(jLabel2)
                    .addComponent(turnLb))
                .addGap(18, 18, 18)
                .addComponent(gameScene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gameSceneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameSceneMouseClicked
        if (!myTurn) {
            return;
        }

        Point point = evt.getPoint();

        // Get Component: GameScene -> CaroScene -> JLabel?
        Object object = evt.getComponent().getComponentAt(point).getComponentAt(point);
        if (!(object instanceof JLabel)){
            return;
        }

        Coordinate coordinate = new Coordinate(
                point.x / oneBlockSize,
                point.y / oneBlockSize,
                player);
        this.playerMove(coordinate);
    }//GEN-LAST:event_gameSceneMouseClicked

    private void gameSceneComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_gameSceneComponentRemoved
        this.disconnect();
    }//GEN-LAST:event_gameSceneComponentRemoved

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.disconnect();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gameScene;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel playerNameLb;
    private javax.swing.JLabel turnLb;
    // End of variables declaration//GEN-END:variables
}
